#!/usr/bin/env python3
"""
Reads assets/models/Lava.glb and where it is placed in assets/scene/main.composite, and writes
src/shared/lavaShape.ts: the lava surface as triangles in world X/Z coordinates.

The game uses it for (1) bubbles that only appear on the real lava surface and (2) the "touching lava
eliminates you" check. Re-run it whenever you reshape or move Lava.glb in the editor:

    npm run lava
"""
import json, math, struct, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GLB = ROOT / 'assets/models/Lava.glb'
COMPOSITE = ROOT / 'assets/scene/main.composite'
OUT = ROOT / 'src/shared/lavaShape.ts'


def load_glb(path):
    b = path.read_bytes()
    jlen = struct.unpack('<I', b[12:16])[0]
    j = json.loads(b[20:20 + jlen])
    off = 20 + jlen
    blen = struct.unpack('<I', b[off:off + 4])[0]
    return j, b[off + 8:off + 8 + blen]


def read_accessor(j, binb, index):
    a = j['accessors'][index]
    bv = j['bufferViews'][a['bufferView']]
    base = bv.get('byteOffset', 0) + a.get('byteOffset', 0)
    ncomp = {'SCALAR': 1, 'VEC2': 2, 'VEC3': 3, 'VEC4': 4}[a['type']]
    fmt = {5126: 'f', 5123: 'H', 5125: 'I', 5121: 'B'}[a['componentType']]
    size = struct.calcsize(fmt)
    stride = bv.get('byteStride') or size * ncomp
    return [struct.unpack('<' + fmt * ncomp, binb[base + i * stride: base + i * stride + size * ncomp]) for i in range(a['count'])]


def trs(translation, rotation, scale):
    x, y, z, w = rotation
    r = [[1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
         [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
         [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)]]
    m = [[r[i][c] * scale[c] for c in range(3)] + [translation[i]] for i in range(3)]
    return m + [[0, 0, 0, 1]]


def mul(a, b):
    return [[sum(a[i][k] * b[k][j] for k in range(4)) for j in range(4)] for i in range(4)]


def entity_matrix():
    comp = json.loads(COMPOSITE.read_text())
    data = {c['name']: c['data'] for c in comp['components']}
    for entity, g in data['core::GltfContainer'].items():
        if g['json']['src'].endswith('Lava.glb'):
            t = data['core::Transform'][entity]['json']
            p, r, s = t['position'], t['rotation'], t['scale']
            return trs([p['x'], p['y'], p['z']], [r['x'], r['y'], r['z'], r['w']], [s['x'], s['y'], s['z']])
    sys.exit('Lava.glb is not placed in main.composite')


def main():
    j, binb = load_glb(GLB)
    nodes = j['nodes']
    base = entity_matrix()
    tris, surface_y = [], []

    def walk(i, parent):
        n = nodes[i]
        m = mul(parent, trs(n.get('translation', [0, 0, 0]), n.get('rotation', [0, 0, 0, 1]), n.get('scale', [1, 1, 1])))
        if 'mesh' in n:
            for prim in j['meshes'][n['mesh']]['primitives']:
                pos = read_accessor(j, binb, prim['attributes']['POSITION'])
                idx = [v[0] for v in read_accessor(j, binb, prim['indices'])] if 'indices' in prim else list(range(len(pos)))
                world = [tuple(sum(m[r][c] * [p[0], p[1], p[2], 1][c] for c in range(4)) for r in range(3)) for p in pos]
                for k in range(0, len(idx), 3):
                    a, b, c = world[idx[k]], world[idx[k + 1]], world[idx[k + 2]]
                    if abs((b[0] - a[0]) * (c[2] - a[2]) - (c[0] - a[0]) * (b[2] - a[2])) > 1e-6:
                        tris.append([a[0], a[2], b[0], b[2], c[0], c[2]])
                        surface_y.extend([a[1], b[1], c[1]])
        for child in n.get('children', []):
            walk(child, m)

    identity = [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
    for root in j['scenes'][0]['nodes']:
        walk(root, mul(identity, base))

    lines = [
        '// GENERATED by scripts/generate-lava-shape.py from assets/models/Lava.glb. Do not edit; run `npm run lava`.',
        '',
        '/** The lava surface as triangles in world X/Z: [ax, az, bx, bz, cx, cz]. */',
        'export const LAVA_TRIANGLES: number[][] = [',
    ]
    lines += ['  [' + ', '.join(f'{v:.2f}' for v in t) + '],' for t in tris]
    lines += [']', '', f'export const LAVA_GENERATED_SURFACE_Y = {sum(surface_y) / len(surface_y):.2f}', '']
    OUT.write_text('\n'.join(lines))
    xs = [t[i] for t in tris for i in (0, 2, 4)]
    zs = [t[i] for t in tris for i in (1, 3, 5)]
    print(f'{len(tris)} triangles, x {min(xs):.1f}..{max(xs):.1f}, z {min(zs):.1f}..{max(zs):.1f}, surface y {sum(surface_y) / len(surface_y):.2f} -> {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
